### ISSUE TITLE
missing become?

### ISSUE THREAD

**Issue by cdmo** [tulibraries/ansible-role-passenger-apache#2]
on `setup-RedHat.yml` you're missing a `  become: yes`. You need sudo to add a repo to `yum`. Maybe irrelevant to you, but something I just noticed while poking around here.

**Comment by cmharlow** [comment]
thanks @cdmo - and sorry for the delay in responding. i'll look to add along with some other stock ansible testing & docs we're adding soon. thanks!

**Comment by cmharlow** [comment]
Done by cleanup branch. Sorry took so long to close.
